### ISSUE TITLE
Difficulties installing readstat-rs on Windows 11

### ISSUE THREAD

**Issue by cdeakin-unsw** [curtisalexander/readstat-rs#76]
Hi @curtisalexander I'm very keen to use readstat-rs for my analyses at University of New South Wales, Sydney, Australia but unfortunately not having any luck with installing it on Windows 11. Would it be possible to get some guidance? Thank you in advance, Claire

**Comment by curtisalexander** [comment]
Can you share more details on the issue you are facing? And how are you installing now - just downloading the binary? To help troubleshoot or give guidance I would need to better understand what has been done and the exact problem with the installation. 

Finally, I don’t have a Win 11 machine (binaries are built with GitHub Actions on Windows Server 2022) and so could only give guidance and wouldn’t be able to test myself.

**Comment by cdeakin-unsw** [comment]
Hi @curtisalexander thanks so much for getting back to me. I wanted to try a bit more troubleshooting and it turns out it was a lot more simple than I thought and I didn't need to install with cargo or use MSVC. I'll just post a couple of tips in case it helps any future users:

1. During the installation of LLVM, selecting the option "Add LLVM to the system PATH for all users" set the LIBCLANG_PATH correctly
2. After extracting the v0.11.0 release for Windows into a directory called "C:\Software\readstat-v0.11.0-x86_64-pc-windows-msvc", readstat can be run in Windows Command Prompt using C:\Software\readstat-v0.11.0-x86_64-pc-windows-msvc\readstat.exe 

Thank you again, I think readstat will help make my analyses more efficient. Let me know if there is a way to acknowledge you.

**Comment by curtisalexander** [comment]
@cdeakin-unsw - I am so glad that you got things working.  In terms of acknowledgement - I don’t need anything specific but appreciate you asking.  However, I would be interested to hear how you are utilizing and if it does end up being of use!
